name: Releasefdsafsad
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test release
        id: release
        run: |
          NEW_TAG="v1.2.${{ github.run_number }}"
          echo "new_release_git_tag=$NEW_TAG" >> $GITHUB_OUTPUT
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: 'ReVanced Patches $steps.release.outputs.new_release_git_tag'
          subject-path: 'patches-!(*sources*|*javadoc*).rvp'
